### ISSUE TITLE
Compilation Failures in Both UE 5.5 and 5.6 - Missing Include Directives

### ISSUE THREAD

**Issue by zachmonkey** [kevinpbuckley/VibeUE#7]
## Summary
VibeUE fails to compile in both Unreal Engine 5.5 and 5.6 with multiple "incomplete type" and "undefined identifier" errors, despite the repository stating UE 5.6+ is the minimum supported version. The Build.cs file contains all necessary module dependencies, but source files are missing required #include directives.

## Environment

**Tested Configurations:**
- **Configuration 1:** Unreal Engine 5.6, Visual Studio 2022 (14.38.33145), Windows 10.0.22621.0 SDK
- **Configuration 2:** Unreal Engine 5.5, Visual Studio 2022 (14.38.33145), Windows 10.0.22621.0 SDK

**Plugin Version:** Latest from main branch (cloned October 2, 2025)

### Setup
1. Install Unreal Engine 5.6 or 5.5 via Epic Games Launcher
2. Create a new blank C++ project
3. Close Unreal Engine
4. Navigate to project directory and create `Plugins` folder if it doesn't exist
5. Clone VibeUE into Plugins folder:
   ```bash
   cd "C:\Path\To\YourProject\Plugins"
   git clone https://github.com/kevinpbuckley/VibeUE.git
   ```

### Compilation Attempt
6. Open the `.uproject` file
7. When prompted "Would you like to rebuild VibeUE now?", click **Yes**
8. Observe compilation errors

**Alternative compilation method (same results):**
- Right-click `.uproject` → Generate Visual Studio project files
- Open `.sln` in Visual Studio
- Build → Build Solution

## Expected Behavior
VibeUE should compile successfully in UE 5.6+ as stated in the repository README.

## Actual Behavior
Compilation fails with multiple errors across several source files.

### CommonUtils.cpp
```
CommonUtils.cpp: error C2065: 'FKismetEditorUtilities': undeclared identifier
CommonUtils.cpp: error C2228: left of '.CreateBlueprint' must have class/struct/union
```

### BlueprintComponentReflection.cpp
```
BlueprintComponentReflection.cpp: error C2079: 'USCS_Node' uses undefined class 'USCS_Node'
BlueprintComponentReflection.cpp: error C2065: 'UK2Node': undeclared identifier
```

### BlueprintReflection.cpp
```
BlueprintReflection.cpp: incomplete type errors for Blueprint-related classes
```

## Root Cause Analysis

The Build.cs file correctly declares all necessary module dependencies:

```csharp
PublicDependencyModuleNames.AddRange(
    new string[]
    {
        "Core",
        "CoreUObject",
        "Engine",
        "InputCore",
        "Networking",
        "Sockets",
        "HTTP",
        "Json",
        "JsonUtilities",
        "DeveloperSettings"
    }
);

PrivateDependencyModuleNames.AddRange(
    new string[]
    {
        "UnrealEd",
        "EditorScriptingUtilities",
        "EditorSubsystem",
        "Slate",
        "SlateCore",
        "UMG",
        "Kismet",
        "KismetCompiler",
        "BlueprintGraph",
        // ... and more
    }
);
```

However, the **source files themselves are missing the corresponding #include directives**.

## Suspected Missing Includes

Based on the errors, these files likely need additional includes:

**CommonUtils.cpp:**
```cpp
#include "Kismet2/KismetEditorUtilities.h"
#include "Kismet2/BlueprintEditorUtils.h"
```

**BlueprintComponentReflection.cpp:**
```cpp
#include "Engine/SCS_Node.h"
#include "K2Node.h"
#include "EdGraph/EdGraphNode.h"
```

**BlueprintReflection.cpp:**
```cpp
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
```

**Comment by kevinpbuckley** [comment]
https://discord.gg/hZs73ST59a

Buckley603 on Discord.  Working today but Ill be on there tonight.
